# Jekyll Resume Theme Settings
# ----------------------------

# Site Settings
title: "Modern Resume Template"
#baseurl: "jekyll-resume-template"

# Global Variables - same on every resume
resume_name: "Some Body"

# Contact info, displayed in banner
resume_contact:
  email: "somebody@somewhere.org"
  phone: "123-456-7891"
  linkedin: "https://www.linkedin.com/"
  github: "https://github.com/"

# Resume Sections:
# Comment/un-comment sections to exclude/include in resume
resume_section_about: true
resume_section_projects: true
resume_section_skills: true
resume_section_work: true
resume_section_education: true

# Default Resume Settings
defaults:
#------------------LETTER DEFAULTS------------------#
  - scope:
      path: "letters/*"
    values:
      layout: "letter"
      letter_title: Lorem
      layout: letter
      company: FakeCompany
      position: CIO
      posting_id: "0070010122"

#------------------RESUME DEFAULTS------------------#
  - scope:
      path: "resumes/*"
    values:
      layout: "resume"



      #(1) > CUT/PASTE THE FOLLOWING VARIABLES TO YOUR RESUME FRONT-MATTER
      #(2)> Edit the numbers to include the entries you want, or leave blank to include all entries

      resume_title: "Job Title"
      # Only include one 'About Me' Statement
      about: 1

      # Specify project ID's from _data/projects, separated by comma
      projects: [1, 2]

      # Specify Skillset name from _data/skills
      skills: other-skills

      # Specify work ID's from _data/work
      work: [1, 2]

      # Specify education ID's from _data/education
      education: [1, 2]

      #----------------------------------------------------------------
