# Site Settings
title: "Modern Resume Template"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Resume settings
# @TODO: add color variations integration
# resume_color:             ""
# Your name, as it will appear on the resume
resume_name: "John Doe"

# Contact info, displayed in banner
resume_header_links:
  resume_header_email: "somebody@somewhere.org"
  resume_header_phone: "123-456-7891"
  resume_header_linkedin: "https://www.linkedin.com/"
  resume_header_github: "https://github.com/"

# Resume Sections:
# Comment/un-comment sections to exclude/include in resume
resume_section_about: true
resume_section_projects: true
resume_section_skills: true
resume_section_work: true
resume_section_education: true
