# Site Settings
title: "Modern Resume Template"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Resume settings
resume_color:             ""
resume_name:              "John Doe"
resume_title:             "VP of Being John Doe"

# Resume Sections: 
# comment out to exclude
resume_section_about:     true
resume_section_projects:  true
resume_section_skills:    true
resume_section_work:      true
resume_section_education: true